port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254

proxies:
  - name: Amazon.com
    server: support.vidio.com
    port: 443
    type: vless
    uuid: 22dccf03-83fc-433b-b2b6-e0cebb41f29c
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: hitamlegam.xosaseg971.workers.dev
    network: ws
    ws-opts:
      path: /43.218.77.16-1443
      headers:
        Host: hitamlegam.xosaseg971.workers.dev
    udp: true
  - name: Akamai Connected Cloud
    server: support.vidio.com
    port: 443
    type: vless
    uuid: 22dccf03-83fc-433b-b2b6-e0cebb41f29c
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: hitamlegam.xosaseg971.workers.dev
    network: ws
    ws-opts:
      path: /172.232.239.151-587
      headers:
        Host: hitamlegam.xosaseg971.workers.dev
    udp: true
  - name: Alibaba
    server: support.vidio.com
    port: 443
    type: vless
    uuid: 22dccf03-83fc-433b-b2b6-e0cebb41f29c
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: hitamlegam.xosaseg971.workers.dev
    network: ws
    ws-opts:
      path: /8.215.196.18-587
      headers:
        Host: hitamlegam.xosaseg971.workers.dev
    udp: true
  - name: 2 Akamai Connected Cloud 
    server: support.vidio.com
    port: 443
    type: vless
    uuid: 22dccf03-83fc-433b-b2b6-e0cebb41f29c
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: hitamlegam.xosaseg971.workers.dev
    network: ws
    ws-opts:
      path: /172.232.237.112-2053
      headers:
        Host: hitamlegam.xosaseg971.workers.dev
    udp: true
  - name: 2 Amazon.com
    server: support.vidio.com
    port: 443
    type: vless
    uuid: 22dccf03-83fc-433b-b2b6-e0cebb41f29c
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: hitamlegam.xosaseg971.workers.dev
    network: ws
    ws-opts:
      path: /43.218.77.16-443
      headers:
        Host: hitamlegam.xosaseg971.workers.dev
    udp: true
  - name: PT Pusat Media Indonesia
    server: support.vidio.com
    port: 443
    type: vless
    uuid: 22dccf03-83fc-433b-b2b6-e0cebb41f29c
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: hitamlegam.xosaseg971.workers.dev
    network: ws
    ws-opts:
      path: /103.6.207.108-8080
      headers:
        Host: hitamlegam.xosaseg971.workers.dev
    udp: true
  - name: First Cagayan Converge Data Center Inc
    server: support.vidio.com
    port: 443
    type: vless
    uuid: 22dccf03-83fc-433b-b2b6-e0cebb41f29c
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: hitamlegam.xosaseg971.workers.dev
    network: ws
    ws-opts:
      path: /203.194.112.119-2053
      headers:
        Host: hitamlegam.xosaseg971.workers.dev
    udp: true
  - name: 2 First Cagayan Converge Data Center Inc
    server: support.vidio.com
    port: 443
    type: vless
    uuid: 22dccf03-83fc-433b-b2b6-e0cebb41f29c
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: hitamlegam.xosaseg971.workers.dev
    network: ws
    ws-opts:
      path: /203.194.112.119-8443
      headers:
        Host: hitamlegam.xosaseg971.workers.dev
    udp: true
  - name: PT Telkom Indonesia
    server: support.vidio.com
    port: 443
    type: vless
    uuid: 6d231278-54e1-4c90-8b2b-8cc2166b9c2a
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: hitamlegam.xosaseg971.workers.dev
    network: ws
    ws-opts:
      path: /36.95.152.58-12137
      headers:
        Host: hitamlegam.xosaseg971.workers.dev
    udp: true
    
proxy-groups:
  - name: ID-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - Amazon.com
      - Akamai Connected Cloud
      - Alibaba
      - 2 Akamai Connected Cloud 
      - 2 Amazon.com
      - PT Pusat Media Indonesia
      - First Cagayan Converge Data Center Inc
      - 2 First Cagayan Converge Data Center Inc
      - PT Telkom Indonesia

  - name: MIX-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - Amazon.com
      - Akamai Connected Cloud
      - Alibaba
      - 2 Akamai Connected Cloud 
      - 2 Amazon.com
      - PT Pusat Media Indonesia
      - First Cagayan Converge Data Center Inc
      - 2 First Cagayan Converge Data Center Inc
      - PT Telkom Indonesia
      
  - name: IKLAN
    type: select
    proxies:
     - MIX-X
     - REJECT

  - name: GAME
    type: select
    proxies:
     - ID-X
     - DIRECT
     - REJECT

  - name: pilih
    type: select
    proxies:
      - Amazon.com
      - Akamai Connected Cloud
      - Alibaba
      - 2 Akamai Connected Cloud 
      - 2 Amazon.com
      - PT Pusat Media Indonesia
      - First Cagayan Converge Data Center Inc
      - 2 First Cagayan Converge Data Center Inc
      - PT Telkom Indonesia

rules:
 - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
 - RULE-SET,Block,IKLAN
 - RULE-SET,Game,GAME
 - RULE-SET,Umum,MIX-X
 - RULE-SET,indo,ID-X
 - RULE-SET,Sosmed,MIX-X
 - RULE-SET,Streaming,MIX-X
 - RULE-SET,Bankid,ID-X
 - RULE-SET,Tiktok,MIX-X
 - RULE-SET,Meta,MIX-X
 - RULE-SET,PortGame,GAME
 - MATCH,MIX-X


rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./game.yaml 
  PortGame:
    type: file
    behavior: classical
    path: ./portgame.yaml
  Umum:
    type: file
    behavior: classical
    path: ./umum.yaml 
  indo:
    type: file
    behavior: classical
    path: ./indo.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./sosmed.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./streaming.yaml
  Bankid:
    type: file
    behavior: domain
    path: ./bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./meta.yaml
  Block:
    type: file
    behavior: domain
    path: ./block.yaml  
